<?php

namespace MicroBundle\Repository;

/**
 * BuildDeviceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BuildDeviceRepository extends \Doctrine\ORM\EntityRepository
{

}
