<?php

namespace MicroBundle\Repository;

/**
 * DeviceNameRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DeviceNameRepository extends \Doctrine\ORM\EntityRepository
{
}
