<?php

namespace MicroBundle\Repository;

/**
 * DocDeviceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DocDeviceRepository extends \Doctrine\ORM\EntityRepository
{
}
