<?php

namespace MicroBundle\Repository;

/**
 * documentInspectorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DocumentInspectorRepository extends \Doctrine\ORM\EntityRepository
{
}
