<?php

namespace MicroBundle\Repository;

/**
 * FireProtectionDeviceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FireProtectionDeviceRepository extends \Doctrine\ORM\EntityRepository
{

}
