<?php

namespace MicroBundle\Repository;
/**
 * FireInspectionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FireInspectionRepository extends \Doctrine\ORM\EntityRepository

{
    /**
     * @param $id
     * @return mixed
     */
    public function findAllExceptId($id) {
        $qb = $this->createQueryBuilder('FireInspection');
        $qb->add('select', 'f')
            ->add('from', 'MicroBundle:FireInspection f')
            ->add('where', 'f != :id')
            ->setParameter('id', $id);
        return $qb->getQuery()->getResult();
    }

}
