<?php

namespace MicroBundle\Repository;

/**
 * FireInspectionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FireInspectionRepository extends \Doctrine\ORM\EntityRepository
{
}
