<?php

namespace MicroBundle\Repository;

/**
 * InspectedDeviceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InspectedDeviceRepository extends \Doctrine\ORM\EntityRepository
{
}
