<?php

namespace MicroBundle\Repository;

/**
 * LoopDevRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LoopDevRepository extends \Doctrine\ORM\EntityRepository
{
}
