<?php

namespace MicroBundle\Repository;
use Doctrine\Bundle\DoctrineBundle\Repository\ServiceEntityRepository;
use Doctrine\ORM\EntityManagerInterface;
use MicroBundle\Entity\MyCompany;
use Symfony\Bridge\Doctrine\RegistryInterface;

/**
 * MyCompanyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
final class MyCompanyRepository extends ServiceEntityRepository
{
    /**
     * MyCompanyRepository constructor.
     * @param RegistryInterface $registry
     */
    public function __construct(RegistryInterface $registry)
    {
        parent::__construct($registry, MyCompany::class);
    }



    public function returnDefaultMyCompany(){
        $myCompany = $this->findOneById(['id' => 1]);

        if ($myCompany == null) {
            $myCompany = new Mycompany('1','Przykładowa nazwa', 'Przykładowa ulica', '00-000',
                'Przykładowe miasto', 'Numer NIP', '000-000-000');
            $em->persist($myCompany);
            $em->flush();
        }
        return $myCompany;
    }
}
