<?php

namespace MicroBundle\Repository;

/**
 * OffertRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OffertRepository extends \Doctrine\ORM\EntityRepository
{
}
