<?php

namespace MicroBundle\Repository;

/**
 * PdfSettingsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PdfSettingsRepository extends \Doctrine\ORM\EntityRepository
{
}
