<?php

namespace MicroBundle\Repository;

/**
 * StampRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StampRepository extends \Doctrine\ORM\EntityRepository
{
}
