<?php

namespace MicroBundle\Repository;

/**
 * TestPositionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TestPositionRepository extends \Doctrine\ORM\EntityRepository
{
}
