
# app/config/security.yml
security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_ADMIN:       ROLE_BOSS
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager
                # if you are using Symfony < 2.8, use the following config instead:
                # csrf_provider: form.csrf_provider

            logout:       true
            anonymous:    ~

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        - { path: ^/register, role: ROLE_SUPER_ADMIN }
        - { path: ^/resetting, role: ROLE_SUPER_ADMIN }
        - { path: ^/user, role: ROLE_ADMIN, requires_channel: https }
        - { path: ^/computer/laptop/\d*/, role: ROLE_ADMIN }
        - { path: ^/computer/laptop/\D, role: ROLE_ADMIN }
        - { path: ^/computer/desktop/\d*/, role: ROLE_ADMIN }
        - { path: ^/computer/desktop/\D, role: ROLE_ADMIN }
        - { path: ^/departament/\d*/, role: ROLE_ADMIN }
        - { path: ^/departament/\D, role: ROLE_ADMIN }
        - { path: ^/employee/\d*/, role: ROLE_ADMIN }
        - { path: ^/employee/\D, role: ROLE_ADMIN }
        - { path: ^/license/\d*/, role: ROLE_ADMIN }
        - { path: ^/license/\D, role: ROLE_ADMIN }
        - { path: ^/printer/\d*/, role: ROLE_ADMIN }
        - { path: ^/printer/\D, role: ROLE_ADMIN }
        - { path: ^/sim/\d*/, role: ROLE_USER }
        - { path: ^/sim/\D, role: ROLE_USER }
        - { path: ^/tablet/\d*/, role: ROLE_ADMIN }
        - { path: ^/tablet/\D, role: ROLE_ADMIN }
        - { path: ^/application, role: ROLE_ADMIN }
        - { path: ^/computerformfactor, role: ROLE_ADMIN }
        - { path: ^/desktopcpu, role: ROLE_ADMIN }
        - { path: ^/desktopram, role: ROLE_ADMIN }
        - { path: ^/document, role: ROLE_ADMIN }
        - { path: ^/gpu, role: ROLE_ADMIN }
        - { path: ^/hdd, role: ROLE_ADMIN }
        - { path: ^/installedapplication, role: ROLE_ADMIN }
        - { path: ^/networkinterfacecard, role: ROLE_ADMIN }
        - { path: ^/opticaldrive, role: ROLE_ADMIN }
        - { path: ^/os, role: ROLE_ADMIN }
        - { path: ^/powersupply, role: ROLE_ADMIN }
        - { path: ^/ssd, role: ROLE_ADMIN }
        - { path: ^/, role: ROLE_USER, requires_channel: https }